myapp/urls.py
from django.urls import path
from .views import (
    home,
    login,
    signup,
    venues,
    logout,
    venuebook,
    order,
    order_cancle,
    change_password,
    
)
app_name = 'myapp'
urlpatterns = [
    path('',home,name='home'),
    path('logindetails',login,name='login'),
    path('signupdetails',signup,name='signup'),
    path('logoutdetails',logout,name='logout'),
    path('venuesdetail',venues,name='venuesdetails'),
    path('venue/book/<id>',venuebook,name='venuebook'),
    path('orders',order,name='orders'),
    path('order/cancle/<id>/', order_cancle, name="Order_Cancle"),
    path('change/password', change_password, name="Change_password")
    
]

venue/urls.py
from django.contrib import admin
from django.urls import path,include
from django.conf import settings
from django.conf.urls.static import static
urlpatterns = [
    path('admin/', admin.site.urls),
    path('',include('myapp.urls')),
]
if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL,document_root=settings.MEDIA_ROOT)

myapp/models.py
from django.db import models
from django.contrib.auth.models import User
from myapp.functions.fileValidation import validate_file_extension
# Create your models here.
class Venue(models.Model):
    vid=models.AutoField(primary_key=True)
    vname=models.CharField(max_length=255, verbose_name='Venue Name')
    vdescriptions=models.TextField(verbose_name='Venue Descripton')
    vtype=models.CharField(max_length=50, verbose_name='Venue Type')
    vaddress=models.CharField(max_length=255, verbose_name='Venue Address')
    vcharges=models.CharField(max_length=15, verbose_name='Venue Charges')
    file = models.FileField(upload_to="uploads/", validators=[validate_file_extension], verbose_name='Venue Image')
    def __str__(self) -> str:
        return self.vname

class Book(models.Model):
    bid=models.AutoField(primary_key=True)
    user=models.ForeignKey(User, on_delete=models.CASCADE, related_name='book_by', verbose_name='Book By')
    venue=models.ForeignKey(Venue, on_delete=models.CASCADE, related_name='venue', verbose_name='Venue Name')
    description=models.CharField(max_length=255, verbose_name="Event Descriptions")
    bookdate=models.DateTimeField(auto_now_add=True, blank=False, verbose_name='Book Date')
    from_date=models.DateField(verbose_name='booking date',null=True, blank=True)
    end_date=models.DateField(verbose_name='end date',null=True, blank=True)
    charges=models.CharField(max_length=25)
    status=models.BooleanField(default=True)

myapp/views.py
from django.shortcuts import render,redirect
from django.http import HttpResponse
from django.contrib.auth.models import User
from django.contrib import messages
import string, random
from django.contrib.auth.hashers import check_password
from datetime import datetime
from .models import Venue,Book
from django.db.models import Q
from django.contrib.auth.decorators import login_required
from django.contrib.auth import authenticate,login as login_details,logout as logout_details
# Create your views here.

def home(request):

    return render(request,'index.html')

def signup(request):
    if request.method == 'POST':
        First_Name = request.POST.get('First_Name')
        Last_Name = request.POST.get('Last_Name')
        Email = request.POST.get('Email')
        Password = request.POST.get('Password')
        Confirm_Password = request.POST.get('ConfirmPassword')
        try:
            if User.objects.filter(email = Email).first():
                messages.warning(request, "Email is already exists,please go to signin")
                return redirect('myapp:signup')
            
            if Password != Confirm_Password:
                messages.warning(request, "please check your confirm password")
                return redirect('myapp:signup')
            str_characters = string.ascii_lowercase + string.digits
            username = ''.join(random.choices(str_characters, k=5))  
            user_obj=User(username=First_Name+'_'+username,first_name=First_Name,last_name=Last_Name,email=Email,)
            user_obj.set_password(Password)
            print(user_obj)
            user_obj.save()
            messages.success(request, "sucessfully registered")
            return redirect('myapp:login')
            
        except Exception as e:
            print(e)
    return render(request,'sign-up.html')

def login(request):
    if request.method == 'POST':
        Email = request.POST.get('Email')
        Password = request.POST.get('Password')
        obj = User.objects.get(email=Email)
        username=obj.username
        print(username)
        user = authenticate(request,email = Email ,password = Password,username=username)
        print(user)
        if user is not None:
            login_details(request, user)
            messages.success(request,f"sucessfully registered {Email}")
            return redirect('myapp:home')
        else:
            messages.warning(request,"login details are incorrect")
            return redirect('myapp:login')
    return render(request,'login.html')
def logout(request):
    logout_details(request)
    messages.success(request,'thank you for spending some moment')
    return redirect('myapp:login')

def venues(request):
    venue_bj=Venue.objects.all()
    contex={
        'venue_bj':venue_bj
    }
    return render(request,'rooms.html',contex)

@login_required(login_url="myapp:login")
def venuebook(request,id):
    venue_obj=Venue.objects.get(vid=id)
    
    if request.method == 'POST':
        
        from_date=request.POST['from_date']
        end_date=request.POST['end_date']
        description=request.POST['description']
        is_available=available(venue_obj,from_date,end_date)
        if is_available:
            Book.objects.create(user=request.user,venue=venue_obj,description=description,from_date=from_date,end_date=end_date,charges=venue_obj.vcharges)
            messages.success(request,f"{request.user}, your booking is sucessfull")
            return redirect('myapp:orders')
        else:
            messages.warning(request,'already booked')

    contex={
        'venue_obj':venue_obj
    }
    return render(request,'room-details.html',contex)

def available(venue,from_date,end_date):
   
    book_obj=Book.objects.filter(
        venue=venue,
        from_date__range=(from_date,end_date)
    )
    return not book_obj

@login_required(login_url="myapp:login")
def order(request):
    contex={
        'book_obj':Book.objects.filter(user=request.user)
    }
    return render(request,'order.html', contex)

@login_required(login_url="myapp:login")
def order_cancle(request, id):
    book_obj = Book.objects.get(bid = id)
    book_obj.status = False
    book_obj.from_date = None
    book_obj.end_date = None
    book_obj.save()

    messages.warning(request, f"{book_obj.venue} cancled successfully")
    return redirect('myapp:orders')

@login_required(login_url="myapp:login")
def change_password(request):
    if request.method == 'POST':
        old_password=request.POST['old_password']
        new_password=request.POST['new_password']
        email = request.POST['email']
        user=User.objects.get(email=email)
        match_password=check_password(old_password,user.password)
        if not match_password:
            messages.warning(request,'old password is not matched')
            return redirect('myapp:Change_password')
        else:
            user.set_password(new_password)
            user.save()
            messages.success(request,'password changed sucessfully')
            return redirect('myapp:Change_password')
    return render(request,'changepassword.html')

myapp/templates/changepassword.html
{% extends 'base.html' %}
{% block body %}
<div class="container">
    
    <div class="col-8 mx-auto">
        <div class="row ">
            {% if messages %}
    {% for messagess in messages %}
    <div class="alert alert-{{messagess.tags}} alert-dismissible fade show" role="alert">
        <strong>{{messagess}}</strong> 
        <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
    </div>
    {% endfor %}
    {% endif %}
            <form method="POST">
                {% csrf_token %}
                <input type="hidden" value="{{request.user.email}}" name="email">
                <h2 class="text-center my-3 mb-5">Change password</h2>
            <div class="form-outline mb-4">
                <input type="password" id="typePasswordX-2" class="form-control form-control-lg" placeholder="old password" name="old_password" required/>
                <!-- <label class="form-label" for="typePasswordX-2">Password</label> -->
            </div>
            <div class="form-outline mb-4">
                <input type="password" id="typePasswordX-2" class="form-control form-control-lg" placeholder="new password" name="new_password" required/>
                <!-- <label class="form-label" for="typePasswordX-2">Password</label> -->
            </div>
            <button type="submit" class="btn btn-primary mt-3 mb-5">change password</button>
            </form>
        </div>
    </div>
</div>
{% endblock %}

myapp/templates/login.html
{% extends 'base.html' %}
{% block title %}login{% endblock %}
{% block body %}
<section class="vh-80">
    <div class="container py-5 h-100">
        <div class="row d-flex justify-content-center align-items-center h-100">
            <div class="col-12 col-md-8 col-lg-6 col-xl-6">
                <div class="card shadow-2-strong"
                    style="border-radius: 1rem; box-shadow: 1px 0px 10px rgba(0, 0, 0,0.2);">
                    <div class="card-body p-5 text-center">
                        {% if messages %}
                        {% for messagess in messages %}
                        <div class="alert alert-{{messagess.tags}}" role="alert">
                            {{messagess}}
                        </div>
                        {% endfor %}
                        {% endif %}
                        <h3 class="mb-5">Login</h3>
                        <form method="POST">
                            {% csrf_token %}
                            <div class="form-outline mb-4">
                                <input type="email" id="typeEmailX-2" class="form-control form-control-lg"
                                    placeholder="Email" name="Email" />
                                <!-- <label class="form-label" for="typeEmailX-2">Email</label> -->
                            </div>

                            <div class="form-outline mb-4">
                                <input type="password" id="typePasswordX-2" class="form-control form-control-lg"
                                    placeholder="Password" name="Password" />
                                <!-- <label class="form-label" for="typePasswordX-2">Password</label> -->
                            </div>

                            <!-- Checkbox -->
                            <div class="form-check d-flex justify-content-start mb-4">
                                <input class="form-check-input" type="checkbox" value="" id="form1Example3" />
                                <label class="form-check-label" for="form1Example3"> Remember password </label>
                            </div>

                            <button class="btn btn-primary btn-lg btn-block" type="submit">Login</button>


                        </form>
                    </div>
                </div>
            </div>
        </div>
    </div>
</section>
{% endblock %}

myapp/templates/order.html
{% extends 'base.html' %}
{% block body %}
{% if messages %}
    {% for messagess in messages %}
    <div class="alert alert-{{messagess.tags}} alert-dismissible fade show" role="alert">
        <strong>{{messagess}}</strong> 
        <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
    </div>
    {% endfor %}
{% endif %}
<div class="container table-responsive py-5"> 
    <table class="table table-bordered table-hover">
      <thead class="thead-dark">
        <tr>
          <th scope="col">Venue</th>
          <th scope="col">Description</th>
          <th scope="col">Bookdate</th>
          <th scope="col">Check in</th>
          <th scope="col">Check out</th>
          <th scope="col">Status</th>
          <th scope="col">Action</th>
        </tr>
      </thead>
      <tbody>
        {% for book in book_obj %}
        <tr>

          <td>{{book.venue}}</td>
          <td>{{book.description}}</td>
          <td>{{book.bookdate}}</td>
          <td>{{book.from_date}}</td>
          <td>{{book.end_date}}</td>
          <td>
            {% if book.status %}
                Booked
            {% else %}
                Cancled
            {% endif %}
          </td>
          <td>
            {% if book.status%}
                <a href="{% url 'myapp:Order_Cancle' book.bid %}" class="btn btn-danger">cancel</a>
            {% endif %}
            </td>
        </tr>
        {% endfor %}
      </tbody>
    </table>
    </div>
    
{% endblock %}

myapp/templates/room-details.html
{% extends 'base.html' %}

{% block body %}
<!-- Breadcrumb Section Begin -->
<div class="breadcrumb-section">
    <div class="container">
        <div class="row">
            <div class="col-lg-12">
                <div class="breadcrumb-text">
                    <h2>Venue Details</h2>
                    
                </div>
            </div>
        </div>
    </div>
</div>
<!-- Breadcrumb Section End -->

<!-- Room Details Section Begin -->
<section class="room-details-section spad">
    <div class="container">
        {% if venue_obj %}
        <div class="row">
            <div class="col-lg-8">
                <div class="room-details-item">
                    <img src="{{venue_obj.file.url}}" alt="ffff">
                    <div class="rd-text">
                        <div class="rd-title">
                            <h3>{{venue_obj.vname}}</h3>
                            <div class="rdt-right">
                                <div class="rating">
                                    <i class="icon_star"></i>
                                    <i class="icon_star"></i>
                                    <i class="icon_star"></i>
                                    <i class="icon_star"></i>
                                    <i class="icon_star-half_alt"></i>
                                </div>
                                
                            </div>
                        </div>
                        <h2>₹{{venue_obj.vcharges}}<span>/Pernight</span></h2>
                        <ul>
                            <li>{{venue_obj.vtype}}</li>
                            <li>{{venue_obj.vaddress}}</li>
                        </ul>
                       <p class="f-para">
                        {{venue_obj.vdescriptions}}
                       </p>
                    </div>
                </div>
                
            </div>
            <div class="col-lg-4">
                <div class="room-booking">
                    <h3>Your Reservation</h3>
                    {% if messages %}
                    {% for messagess in messages %}
                    <div class="alert alert-{{messagess.tags}} alert-dismissible fade show" role="alert">
                        <strong>{{messagess}}</strong> 
                        <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
                    </div>
                    {% endfor %}
                    {% endif %}
                    <form  method="POST">
                        {% csrf_token %}
                        <div class="check-date">
                            <label for="date-in">Check In:</label>
                            <input type="date" class="form-control" id="date-in" name="from_date" required>
                            
                        </div>
                        <div class="check-date">
                            <label for="date-out">Check Out:</label>
                            <input type="date" class="form-control" id="date-out" name="end_date" required>
                           
                        </div>
                        
                        <div>
                            <label for="">Booking description</label>
                            <textarea name="description" id="" cols="30" rows="3" style="width: 100%;"></textarea>
                        </div>
                        <button type="submit">Book Now</button>
                    </form>
                </div>
            </div>
        </div>
        {% endif %}
    </div>
</section>
<!-- Room Details Section End -->
{% endblock %}

myapp/templates/rooms.html
{% extends 'base.html' %}
{% load static %}
{% block title %}
Rooms
{% endblock %}
{% block body %}
    <!-- Breadcrumb Section Begin -->
    <div class="breadcrumb-section">
        <div class="container">
            <div class="row">
                <div class="col-lg-12">
                    <div class="breadcrumb-text">
                        <h2>Our Venues</h2>
                        
                    </div>
                </div>
            </div>
        </div>
    </div>
    <!-- Breadcrumb Section End -->

    <!-- Rooms Section Begin -->
    <section class="rooms-section spad">
        <div class="container">
            <div class="row">
                {% for venue in venue_bj %}
                <div class="col-lg-4 col-md-6">
                    <div class="room-item">
                        <img src="{{venue.file.url}}" alt="" style="width: 150px;height: 250px;">
                        <div class="ri-text">
                            <h4>{{venue.vname}}</h4>
                            <h3>₹{{venue.vcharges}}<span>/Pernight</span></h3>
                            <br>
                            <p>
                                {{venue.vdescriptions}}
                            </p>
                            <ul>
                                <li>
                                    {{venue.vtype}} 
                                </li>
                                <li>
                                    {{venue.vaddress}}
                                </li>
                            </ul>
                            <a href="{% url 'myapp:venuebook' venue.vid %}" class="btn btn-secondary btn-lg" style="width: 100%; margin-top: 10px;">BOOK NOW</a>
                        </div>
                    </div>
                </div>
                {% endfor %}
               
            </div>
        </div>
    </section>
    <!-- Rooms Section End -->
{% endblock %}

myapp/templates/sign-up.html
{% extends 'base.html' %}
{% block title %}Register{% endblock %}
{% block body %}
<section class="vh-80">
    <div class="container py-1 h-100">
        <div class="row d-flex justify-content-center align-items-center h-100">
            <div class="col-12 col-md-8 col-lg-6 col-xl-6">

                <div class="card shadow-2-strong"
                    style="border-radius: 1rem; box-shadow: 1px 0px 10px rgba(0, 0, 0,0.2);">

                    <div class="card-body p-5 text-center">
                        {% if messages %}
                        {% for message in messages %}
                        <div class="alert alert-{{message.tags}}" role="alert">
                            {{message}}
                        </div>
                        {% endfor %}
                        {% endif %}
                        <form method="POST">
                            {% csrf_token %}
                            <h3 class="mb-5">Sign Up</h3>
                            <div class="form-outline mb-4">
                                <input type="text" id="typeFirstnameX-2" class="form-control form-control-lg"
                                    placeholder="First Name" name="First_Name" />
                                <!-- <label class="form-label" for="typeFirstnameX-2">First Name</label> -->
                            </div>
                            <div class="form-outline mb-4">
                                <input type="text" id="typeLastnameX-2" class="form-control form-control-lg"
                                    placeholder="Last Name" name="Last_Name" />
                                <!-- <label class="form-label" for="typeLastnameX-2">Last Name</label> -->
                            </div>

                            <div class="form-outline mb-4">
                                <input type="email" id="typeEmailX-2" class="form-control form-control-lg"
                                    placeholder="Email" name="Email" />
                                <!-- <label class="form-label" for="typeEmailX-2">Email</label> -->
                            </div>

                            <div class="form-outline mb-4">
                                <input type="password" id="typePasswordX-2" class="form-control form-control-lg"
                                    placeholder="Password" name="Password" />
                                <!-- <label class="form-label" for="typePasswordX-2">Password</label> -->
                            </div>
                            <div class="form-outline mb-4">
                                <input type="password" id="typeConfirmPasswordX-2" class="form-control form-control-lg"
                                    placeholder="Confirm_Password" name="ConfirmPassword" />
                                <!-- <label class="form-label" for="typeConfirmPasswordX-2">Confirm Passeord</label> -->
                            </div>

                            <!-- Checkbox -->
                            <div class="form-check d-flex justify-content-start mb-4">
                                <input class="form-check-input" type="checkbox" value="" id="form1Example3" />
                                <label class="form-check-label" for="form1Example3"> Remember password </label>
                            </div>

                            <button class="btn btn-primary btn-lg btn-block" type="submit">Sign Up</button>


                        </form>
                    </div>
                </div>
            </div>
        </div>
    </div>
</section>
<br>
<br>
{% endblock %}